AllCops:
  TargetRubyVersion: 2.3

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrivialAccessors:
  ExactNameMatch: true

Style/CommentIndentation:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

