require: rubocop-rspec

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

# Bundler

Bundler/OrderedGems:
  Enabled: false

# Layout

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

# Lint

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/*.rb

# Metrics

Metrics:
  Enabled: false

# Naming

Naming/PredicateName:
  Enabled: false

# Rails

Rails:
  Enabled: true

# Style

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - features/step_definitions/*.rb

Style/GlobalVars:
  AllowedVariables: [$redis]

Style/MixinUsage:
  Exclude: [bin/*]

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
