Lint/AmbiguousRegexpLiteral:
  Enabled: false

# Configuration parameters: AlignWith, SupportedStyles.
Lint/EndAlignment:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# Configuration parameters: AllowURI.
Metrics/LineLength:
  Max: 120
  Enabled: false

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 45
  Enabled: false

# Configuration parameters: SupportedStyles.
Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AccessorMethodName:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/Documentation:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/HashSyntax:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/OpMethod:
  Enabled: false

# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: false

# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

Lint/DefEndAlignment:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Rails/Validation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

