inherit_from:
  - https://gist.githubusercontent.com/infertux/cdd2ccc6e0a0cd94f458/raw

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false
