require: rubocop-rspec

RSpec/NestedGroups:
  Enabled: false

RSpec/ReturnFromStub:
  Enabled: false

# Bundler

Bundler/OrderedGems:
  Enabled: false

# Layout

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ElseAlignment:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

# Lint

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/*.rb

Lint/EndAlignment:
  Enabled: false

# Metrics

Metrics:
  Enabled: false

# Naming
Naming/PredicateName:
  Enabled: false

# Rails

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

# Style

Style/Documentation:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$redis]

Style/SafeNavigation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
