language: ruby
script: ./bin/ci
rvm:
  - 2.1
  - ruby-head
  - rbx
  - rbx-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: rbx-head
notifications:
  email:
    on_success: always
    on_failure: always
