language: ruby
script: ./bin/ci
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - rbx
  - rbx-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: rbx-head
notifications:
  email:
    on_failure: always
