language: ruby
services:
  - redis-server
before_install: gem update --system --no-doc # https://github.com/sickill/rainbow/issues/49
script: ./bin/ci
after_script: '[ "$TRAVIS_RUBY_VERSION" != "2.3.3" ] || bundle exec rake coveralls:push'
rvm:
- 2.3.3
- 2.4.0
matrix:
  allow_failures:
  - rvm: 2.4.0
notifications:
  email:
    on_failure: always
  slack:
    secure: YLqK6RvH71ZjXEWP84D2AsjDWpG549XE3EQsLizCsURV1VFvDj1g4L9zhVoSAuVj5LLAFSahQqQ1RpZdzaPUtjh72QmHWrOf4lRAS93tH6XTcbIMHCZ8nIO9HX+ErmH8uxEqwiejNxJWvI24hPjfPEtsV2MiJW7Ub2tHABG1WfA=
